### ISSUE TITLE
too much configuration

### ISSUE THREAD

**Issue by alphashuro** [arijs/prettier-miscellaneous#6]
one of `prettier`'s strengths is that it doesn't support too much configuration, and this project initially sold itself as "prettier, but with tabs support". now with so much configuration it has basically become broken, it now formats my files differently from how it did before due to new defaults being added. please make it what it once was

**Comment by rhengles** [comment]
@alphashuro 

I'm sorry, I hadn't much time to keep up with Prettier upstream, I will update this soon.

If you have a specific example of code that is broken, please feel free to open an issue 😊 

However, the main point of this project *now* is to enable users to add whatever configuration option they'd like, as long as it doesn't break compatibility with official Prettier. Tabs support was the first and main one, but now that Prettier has support for tabs and no semicolons, this project need another reason to exist, otherwise you could just use mainstream Prettier. 😃

**Comment by alphashuro** [comment]
thank you for the response, i didn't realize that the mainstream prettier had added the tabs feature :) that solved my one problem with it.
